### ISSUE TITLE
Home directory failed to mount as nosuid

### ISSUE THREAD

**Issue by hitfzyangdianshi** [pwncollege/pwncollege#26]
I have setup this on aws and my local desktop. However, when I reboot the aws instance or reboot my local desktop, then there is an error "Home directory failed to mount as nosuid" when I start a challenge. 

How to solve this issue?

I find a method to solve this issue: ./setup and ./run again, and then delete the new _ctfd:latest docker image, and replace it with the old _ctfd:latest docker image.

I have no idea what the problem is here....

**Comment by ConnorNelson** [comment]
The homes are stored in `.data/homes/data` and `.data/homes/nosuid`, where the latter are `bind,nosuid` mounted to the former. The issue is that these mounts are not persistent across reboots, but the `setup.sh` script is setup to handle remounting if you manually run it again. To further clarify, we need `nosuid` home directories in order to prevent users from smuggling root-owned suid binaries across challenge instances.

Ideally, the system would dynamically handle the home directory mounts, rather than require them to be manually setup prior. The issue with this, though, is that I could not get this easily working. You cannot mount `.data/homes` into some container which will manage the homes dynamically by creating directories and performing `bind,nosuid` mounts in that container, and actually have the `nosuid` portion propagate back to the host, and the ultimately back into a user's container. Even with a `bind-propagation=shared`, the `nosuid` portion is lost.

What I have discovered, however, as discussed in issue #7, is that this `nosuid` portion being lost seems to only be true for `bind` mounts. We can instead switch over to storing the home directories as, for instance, ext4 file systems. This also has the benefit of allowing us to limit storage on home directories, preventing users from being able to fill up the host disk. Ultimately, I just haven't had the time / gotten around to switching the home directories over to this strategy and adding dynamic home directories, which would resolve this issue.

Until the new features get implemented, I would just stick to re-running the scripts on reboot.

**Comment by hitfzyangdianshi** [comment]
Hi.

I just remove build docker part from setup.sh, and keeps mount. after reboot, I run this, and then I start the two nginx-proxy containers(these will be killed or stop after reboot), and the server runs again without nosuid errors. 

```
#!/usr/bin/env bash

set -e

DIR="$(readlink -f $(dirname $0))"
INSTANCE=$1
NUM_USERS=256

if [ -z $1 ]; then
    echo "Usage: $0 <INSTANCE>"
    exit 1
fi


RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

color_echo ()
{
    echo -e "$1$2$NC"
}

cd $DIR




color_echo $YELLOW "[+] Setting up homes"

mkdir -p $DIR/.data/homes
mkdir -p $DIR/.data/homes/data
mkdir -p $DIR/.data/homes/nosuid
for i in $(seq 0 $NUM_USERS); do
    if [ ! -d $DIR/.data/homes/data/$i ]; then
	cp -r /etc/skel $DIR/.data/homes/data/$i
	chown -R ubuntu:ubuntu $DIR/.data/homes/data/$i
    fi
    if [ ! -d $DIR/.data/homes/nosuid/$i ]; then
	mkdir -p $DIR/.data/homes/nosuid/$i
    fi
    if ! mount | grep -q $DIR/.data/homes/nosuid/$i; then
	mount -o bind,nosuid $DIR/.data/homes/data/$i $DIR/.data/homes/nosuid/$i
    fi
done

color_echo $YELLOW "[+] Setting up challenges"

mkdir -p $DIR/.data/challenges
for i in $(seq 0 $NUM_USERS); do
    mkdir -p $DIR/.data/challenges/$i
done
if [ ! -e $DIR/.data/challenges/global ]; then
    pushd $DIR/.data/challenges
    ln -s 0 global
    popd
fi

color_echo $YELLOW "[+] Configuring global resources"

sysctl -w kernel.pty.max=1048576
echo core >/proc/sys/kernel/core_pattern
chmod 666 /var/run/docker.sock

color_echo $YELLOW "[+] Setting up SSH"

if [ -z "$(getent passwd $INSTANCE)" ]; then
    useradd -m $INSTANCE
    usermod -aG docker $INSTANCE
    mkdir -p /home/$INSTANCE/.docker
    cat <<EOF >> /home/$INSTANCE/.docker/config.json
{
    "detachKeys": "ctrl-q,ctrl-q"
}
EOF
fi

if ! grep -q "Match User $INSTANCE" /etc/ssh/sshd_config; then
    cat <<EOF >> /etc/ssh/sshd_config
Match User $INSTANCE
      AuthorizedKeysCommand $DIR/auth.py ${INSTANCE}_db $INSTANCE
      AuthorizedKeysCommandUser root
      X11Forwarding no
      AllowTcpForwarding no
EOF
    service ssh restart
fi


if [ -z "$(docker network ls -q -f name=${INSTANCE}_network)" ]; then
    docker network create "${INSTANCE}_network"
fi
```
